const QR_CODE_REQUEST_GENERATED = "QR_CODE_REQUEST_GENERATED";
const OPEN_CHAT_START = "OPEN_CHAT_START";
const OPEN_CHAT_FAILED = "OPEN_CHAT_FAILED";
const OPEN_CHAT_SUCCEED = "OPEN_CHAT_SUCCEED";

export {
  QR_CODE_REQUEST_GENERATED,
  OPEN_CHAT_START,
  OPEN_CHAT_FAILED,
  OPEN_CHAT_SUCCEED,
};
