const QR_CODE_REQUEST_GENERATED = "QR_CODE_REQUEST_GENERATED";
const OPEN_CHAT_START = "OPEN_CHAT_START";
const OPEN_CHAT_FAILED = "OPEN_CHAT_FAILED";
const OPEN_CHAT_SUCCEED = "OPEN_CHAT_SUCCEED";
const APP_LOADED = "APP_LOADED";

const NEW_GROUP_COMMAND = "NEW_GROUP_COMMAND";
const NEW_COMMUNITY_COMMAND = "NEW_COMMUNITY_COMMAND";
const ARCHIVE_COMMAND = "ARCHIVE_COMMAND";
const SELECT_CHATS_COMMAND = "SELECT_CHATS_COMMAND";
const SETTINGS_COMMAND = "SETTINGS_COMMAND";
const LOGOUT_COMMAND = "LOGOUT_COMMAND";

const CHAT_EXTENDED_HIDE_COMMAND = "CHAT_EXTENDED_HIDE_COMMAND";
const CHAT_SEARCH_HIDE_COMMAND = "CHAT_SEARCH_HIDE_COMMAND";
const CHAT_SEARCH_COMMAND = "CHAT_SEARCH_COMMAND";
const CHAT_INFO_COMMAND = "CHAT_INFO_COMMAND";
const SELECT_CHAT_MESSAGES_COMMAND = "SELECT_CHAT_MESSAGES_COMMAND";
const CLOSE_CHAT_COMMAND = "CLOSE_CHAT_COMMAND";
const MUTE_CHAT_COMMAND = "MUTE_CHAT_COMMAND";
const CLEAR_CHAT_COMMAND = "CLEAR_CHAT_COMMAND";
const DISAPPEARING_CHAT_COMMAND = "DISAPPEARING_CHAT_COMMAND";
const DELETE_CHAT_COMMAND = "DELETE_CHAT_COMMAND";
const REPORT_CHAT_COMMAND = "REPORT_CHAT_COMMAND";
const BLOCK_CHAT_COMMAND = "BLOCK_CHAT_COMMAND";
const CHAT_RESET_OPERATION_COMMAND = "CHAT_RESET_OPERATION_COMMAND";

export {
  QR_CODE_REQUEST_GENERATED,
  OPEN_CHAT_START,
  OPEN_CHAT_FAILED,
  OPEN_CHAT_SUCCEED,
  NEW_GROUP_COMMAND,
  NEW_COMMUNITY_COMMAND,
  ARCHIVE_COMMAND,
  SELECT_CHATS_COMMAND,
  SETTINGS_COMMAND,
  LOGOUT_COMMAND,
  CHAT_EXTENDED_HIDE_COMMAND,
  CHAT_SEARCH_COMMAND,
  CHAT_SEARCH_HIDE_COMMAND,
  CHAT_INFO_COMMAND,
  SELECT_CHAT_MESSAGES_COMMAND,
  CLOSE_CHAT_COMMAND,
  MUTE_CHAT_COMMAND,
  DISAPPEARING_CHAT_COMMAND,
  CLEAR_CHAT_COMMAND,
  DELETE_CHAT_COMMAND,
  REPORT_CHAT_COMMAND,
  BLOCK_CHAT_COMMAND,
  CHAT_RESET_OPERATION_COMMAND,
  APP_LOADED,
};
